<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3bInxFR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3bInxFR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3bInxFR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3bInxFR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3bInxFR\App_KernelDevDebugContainer([
    'container.build_hash' => '3bInxFR',
    'container.build_id' => '1fa0c087',
    'container.build_time' => 1600238496,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3bInxFR');
